-- Seed: obituarios de ejemplo (plantillas) para Funeraria Valderrama
-- Se puede correr las veces que quieras (on conflict do nothing).

-- Permite sembrar/publicar desde el servidor (auth.uid() nulo). Los usuarios
-- autenticados sin rol siguen sin poder publicar.
create or replace function public.enforce_obituario_status()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is not null and not public.is_staff(auth.uid()) then
    if tg_op = 'INSERT' and new.status is distinct from 'draft' then
      raise exception 'Solo admin u owner pueden publicar o archivar';
    elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
      raise exception 'Solo admin u owner pueden cambiar el estado';
    end if;
  end if;
  return new;
end;
$$;

insert into public.obituarios (slug, full_name, photo_url, birth, death, comuna, summary, timeline, gallery, anecdotes, events, status, display_order)
values ('carlos-munoz-rivera', 'Carlos Muñoz Rivera', '/memoriales/obit-1.webp', '12/03/1948', '28/04/2026', 'Concepción', 'Padre dedicado, abuelo cariñoso y profesor jubilado. Dejó una huella imborrable en cada estudiante y en su familia, a quienes amó profundamente.', '[{"year":"1948","title":"Nacimiento","description":"Nace en Chillán, hijo de Pedro y María Luisa."},{"year":"1966","title":"Ingresa a la Universidad de Concepción","description":"Estudia Pedagogía en Historia, su gran vocación."},{"year":"1972","title":"Se casa con Inés","description":"Compañera de vida durante 54 años."},{"year":"1980","title":"Profesor en el Liceo Enrique Molina","description":"Donde enseñó por más de 30 años a generaciones de estudiantes penquistas."},{"year":"2010","title":"Jubilación","description":"Se dedica de lleno a sus nietos y a leer en su jardín."},{"year":"2026","title":"Despedida","description":"Parte rodeado de los suyos, dejando un legado de amor y conocimiento."}]'::jsonb, '[{"src":"/memoriales/memory-1.webp","caption":"Tarde en el jardín con los nietos","author":"Familia"},{"src":"/memoriales/memory-2.webp","caption":"El día del matrimonio, 1968","author":"Álbum familiar"},{"src":"/memoriales/memory-3.webp","caption":"Cuidando sus rosas, su mayor pasión","author":"Hija mayor"},{"src":"/memoriales/memory-4.webp","caption":"Vacaciones en la costa, verano del 82","author":"Sobrina Carmen"},{"src":"/memoriales/memory-5.webp","caption":"Cumpleaños número 60","author":"Familia"},{"src":"/memoriales/memory-6.webp","caption":"Atardeceres compartidos de toda una vida","author":"Su esposa"}]'::jsonb, '[{"author":"Andrés, su hijo","text":"Cada noche nos contaba una historia distinta antes de dormir. Nunca repetía una."},{"author":"Sofía, su nieta","text":"Me enseñó a leer en su biblioteca. Decía que los libros eran su mejor herencia."},{"author":"Roberto, ex alumno","text":"Gracias a él decidí estudiar historia. Cambió mi vida sin saberlo."}]'::jsonb, '[{"type":"Velatorio","date":"Hoy, 18:00 a 23:00 hrs","address":"Catedral de la Santísima Concepción, Concepción","isoStart":"2026-04-29T18:00:00-03:00","isoEnd":"2026-04-29T23:00:00-03:00","mapsQuery":"Catedral de la Santísima Concepción, Concepción"},{"type":"Misa","date":"Mañana, 11:00 hrs","address":"Catedral de la Santísima Concepción, Concepción","isoStart":"2026-04-30T11:00:00-03:00","isoEnd":"2026-04-30T12:00:00-03:00","mapsQuery":"Catedral de la Santísima Concepción, Concepción"},{"type":"Sepultación","date":"Mañana, 13:30 hrs","address":"Cementerio General de Concepción","isoStart":"2026-04-30T13:30:00-03:00","isoEnd":"2026-04-30T15:00:00-03:00","mapsQuery":"Cementerio General de Concepción"}]'::jsonb, 'published', 0)
on conflict (slug) do nothing;

insert into public.obituarios (slug, full_name, photo_url, birth, death, comuna, summary, timeline, gallery, anecdotes, events, status, display_order)
values ('maria-elena-soto', 'María Elena Soto', '/memoriales/obit-2.webp', '05/07/1942', '26/04/2026', 'Chiguayante', 'Mujer de fe, amante de los jardines y matriarca de una gran familia. Su sonrisa y sus consejos seguirán acompañándonos siempre.', '[{"year":"1942","title":"Nace en Talca","description":"La menor de seis hermanos."},{"year":"1968","title":"Matrimonio con Hernán","description":"Una historia de amor que duró 58 años."},{"year":"1995","title":"Su jardín premiado","description":"Reconocida por la comunidad por sus rosas blancas."},{"year":"2026","title":"Descansa en paz","description":"Rodeada de hijos, nietos y bisnietos."}]'::jsonb, '[{"src":"/memoriales/memory-1.webp","caption":"Tarde en el jardín con los nietos","author":"Familia"},{"src":"/memoriales/memory-2.webp","caption":"El día del matrimonio, 1968","author":"Álbum familiar"},{"src":"/memoriales/memory-3.webp","caption":"Cuidando sus rosas, su mayor pasión","author":"Hija mayor"},{"src":"/memoriales/memory-4.webp","caption":"Vacaciones en la costa, verano del 82","author":"Sobrina Carmen"},{"src":"/memoriales/memory-5.webp","caption":"Cumpleaños número 60","author":"Familia"},{"src":"/memoriales/memory-6.webp","caption":"Atardeceres compartidos de toda una vida","author":"Su esposa"}]'::jsonb, '[{"author":"Hernán, su esposo","text":"Cada mañana me preparaba el café. Cincuenta y ocho años. Nunca falló."},{"author":"Daniela, su nieta","text":"Su casa olía siempre a pan amasado. Voy a extrañar ese olor."},{"author":"Juan, su hijo","text":"Nunca la vi enojada. Esa era su gran fortaleza."}]'::jsonb, '[{"type":"Velatorio","date":"Mañana, 11:00 a 18:00 hrs","address":"Capilla Valderrama, O''Higgins 1601, Concepción","isoStart":"2026-04-30T11:00:00-03:00","isoEnd":"2026-04-30T18:00:00-03:00","mapsQuery":"Capilla Valderrama, O''Higgins 1601, Concepción"}]'::jsonb, 'published', 1)
on conflict (slug) do nothing;

insert into public.obituarios (slug, full_name, photo_url, birth, death, comuna, summary, timeline, gallery, anecdotes, events, status, display_order)
values ('jorge-andres-pereira', 'Jorge Andrés Pereira', '/memoriales/obit-3.webp', '22/11/1965', '25/04/2026', 'San Pedro de la Paz', 'Empresario, amigo leal y apasionado del fútbol. Vivió cada día con intensidad y enseñó a los suyos el valor del trabajo y la honestidad.', '[{"year":"1965","title":"Nace en Concepción","description":"El segundo de tres hermanos."},{"year":"1988","title":"Egresa de Ingeniería Comercial","description":"Universidad de Concepción."},{"year":"1995","title":"Funda su empresa","description":"Una constructora que llegó a emplear a más de 200 personas."},{"year":"2003","title":"Llegan los gemelos","description":"Tomás y Vicente, su mayor orgullo."},{"year":"2026","title":"Despedida","description":"Demasiado pronto, pero con una vida intensa y bien vivida."}]'::jsonb, '[{"src":"/memoriales/memory-1.webp","caption":"Tarde en el jardín con los nietos","author":"Familia"},{"src":"/memoriales/memory-2.webp","caption":"El día del matrimonio, 1968","author":"Álbum familiar"},{"src":"/memoriales/memory-3.webp","caption":"Cuidando sus rosas, su mayor pasión","author":"Hija mayor"},{"src":"/memoriales/memory-4.webp","caption":"Vacaciones en la costa, verano del 82","author":"Sobrina Carmen"},{"src":"/memoriales/memory-5.webp","caption":"Cumpleaños número 60","author":"Familia"},{"src":"/memoriales/memory-6.webp","caption":"Atardeceres compartidos de toda una vida","author":"Su esposa"}]'::jsonb, '[{"author":"Tomás, su hijo","text":"Me enseñó que perder con dignidad es ganar. En la cancha y en la vida."},{"author":"Loreto, su esposa","text":"Bailamos en la cocina cada viernes. Nunca lo voy a olvidar."},{"author":"Pedro, socio","text":"Su palabra valía más que cualquier contrato. Así de simple."},{"author":"Vicente, su hijo","text":"Hincha de Universidad de Concepción hasta el último día."}]'::jsonb, '[{"type":"Velatorio","date":"Hoy, 19:00 a 23:00 hrs","address":"Parroquia San Pedro Apóstol, San Pedro de la Paz","isoStart":"2026-04-29T19:00:00-03:00","isoEnd":"2026-04-29T23:00:00-03:00","mapsQuery":"Parroquia San Pedro Apóstol, San Pedro de la Paz"},{"type":"Misa","date":"Mañana, 12:00 hrs","address":"Parroquia San Pedro Apóstol, San Pedro de la Paz","isoStart":"2026-04-30T12:00:00-03:00","isoEnd":"2026-04-30T13:00:00-03:00","mapsQuery":"Parroquia San Pedro Apóstol, San Pedro de la Paz"}]'::jsonb, 'published', 2)
on conflict (slug) do nothing;

insert into public.obituarios (slug, full_name, photo_url, birth, death, comuna, summary, timeline, gallery, anecdotes, events, status, display_order)
values ('rosa-vargas-leiva', 'Rosa Vargas Leiva', '/memoriales/obit-4.webp', '30/01/1939', '24/04/2026', 'Talcahuano', 'Costurera durante más de 50 años, madre de cinco y bisabuela orgullosa. Su hogar siempre fue un refugio cálido para todos.', '[{"year":"1939","title":"Nace en Cañete","description":"En una familia campesina."},{"year":"1961","title":"Se casa con Luis","description":"Compañero de toda la vida."},{"year":"1965","title":"Abre su taller","description":"En el living de su casa, vistió a tres generaciones del barrio."},{"year":"2026","title":"Despedida","description":"Rodeada de hijos, nietos y bisnietos."}]'::jsonb, '[{"src":"/memoriales/memory-1.webp","caption":"Tarde en el jardín con los nietos","author":"Familia"},{"src":"/memoriales/memory-2.webp","caption":"El día del matrimonio, 1968","author":"Álbum familiar"},{"src":"/memoriales/memory-3.webp","caption":"Cuidando sus rosas, su mayor pasión","author":"Hija mayor"},{"src":"/memoriales/memory-4.webp","caption":"Vacaciones en la costa, verano del 82","author":"Sobrina Carmen"},{"src":"/memoriales/memory-5.webp","caption":"Cumpleaños número 60","author":"Familia"},{"src":"/memoriales/memory-6.webp","caption":"Atardeceres compartidos de toda una vida","author":"Su esposa"}]'::jsonb, '[{"author":"Patricia, su hija","text":"Cosió mi vestido de novia con sus manos. Lloraba mientras lo hacía."},{"author":"Luis, su esposo","text":"Bailamos cueca cada 18 de septiembre. Nunca falló."},{"author":"Camila, su bisnieta","text":"Me hizo un osito de retazos. Lo tengo en mi cama."}]'::jsonb, '[{"type":"Velatorio","date":"Hoy, 17:00 a 22:00 hrs","address":"Parroquia San José, Talcahuano","isoStart":"2026-04-29T17:00:00-03:00","isoEnd":"2026-04-29T22:00:00-03:00","mapsQuery":"Parroquia San José, Talcahuano"},{"type":"Sepultación","date":"Mañana, 11:00 hrs","address":"Cementerio Parque Talcahuano","isoStart":"2026-04-30T11:00:00-03:00","isoEnd":"2026-04-30T12:30:00-03:00","mapsQuery":"Cementerio Parque Talcahuano"}]'::jsonb, 'published', 3)
on conflict (slug) do nothing;

insert into public.obituarios (slug, full_name, photo_url, birth, death, comuna, summary, timeline, gallery, anecdotes, events, status, display_order)
values ('patricia-fuentes-reyes', 'Patricia Fuentes Reyes', '/memoriales/obit-5.webp', '14/09/1958', '23/04/2026', 'Hualpén', 'Enfermera de vocación, viajera incansable y voluntaria comunitaria. Dedicó su vida a cuidar de los demás con ternura y entrega.', '[{"year":"1958","title":"Nace en Talcahuano","description":"A pasos del mar que tanto amó."},{"year":"1980","title":"Titulada como enfermera","description":"Universidad de Concepción."},{"year":"1985","title":"Hospital Las Higueras","description":"Donde trabajó por más de 35 años."},{"year":"2026","title":"Descanso","description":"Tras una vida de servicio."}]'::jsonb, '[{"src":"/memoriales/memory-1.webp","caption":"Tarde en el jardín con los nietos","author":"Familia"},{"src":"/memoriales/memory-2.webp","caption":"El día del matrimonio, 1968","author":"Álbum familiar"},{"src":"/memoriales/memory-3.webp","caption":"Cuidando sus rosas, su mayor pasión","author":"Hija mayor"},{"src":"/memoriales/memory-4.webp","caption":"Vacaciones en la costa, verano del 82","author":"Sobrina Carmen"},{"src":"/memoriales/memory-5.webp","caption":"Cumpleaños número 60","author":"Familia"},{"src":"/memoriales/memory-6.webp","caption":"Atardeceres compartidos de toda una vida","author":"Su esposa"}]'::jsonb, '[{"author":"Mario, su esposo","text":"Veíamos cada atardecer desde la Península de Hualpén. Ese era nuestro ritual."},{"author":"Compañera Andrea","text":"Era la primera en llegar al turno y la última en irse. Siempre."},{"author":"Fernanda, sobrina","text":"Me enseñó a no tenerle miedo a la vida. Ni a la muerte."}]'::jsonb, '[{"type":"Velatorio","date":"Hoy, 19:30 hrs","address":"Parroquia Santa Sofía, Hualpén","isoStart":"2026-04-29T19:30:00-03:00","isoEnd":"2026-04-29T23:00:00-03:00","mapsQuery":"Parroquia Santa Sofía, Hualpén"}]'::jsonb, 'published', 4)
on conflict (slug) do nothing;

insert into public.obituarios (slug, full_name, photo_url, birth, death, comuna, summary, timeline, gallery, anecdotes, events, status, display_order)
values ('luis-gonzalez-tapia', 'Luis González Tapia', '/memoriales/obit-6.webp', '08/06/1944', '21/04/2026', 'Coronel', 'Pescador, narrador de historias y querido vecino. Amaba el mar al que volvía cada amanecer, dejando un legado de bondad y trabajo.', '[{"year":"1944","title":"Nace en Coronel","description":"Hijo y nieto de pescadores."},{"year":"1960","title":"Su primer bote","description":"Llamado ''La Estrella del Norte''."},{"year":"1968","title":"Se casa con Gladys","description":"Su gran amor."},{"year":"2010","title":"Cuenta historias en la caleta","description":"Se convierte en el narrador favorito de los niños del pueblo."},{"year":"2026","title":"Despedida","description":"Volvió al mar que tanto amó."}]'::jsonb, '[{"src":"/memoriales/memory-1.webp","caption":"Tarde en el jardín con los nietos","author":"Familia"},{"src":"/memoriales/memory-2.webp","caption":"El día del matrimonio, 1968","author":"Álbum familiar"},{"src":"/memoriales/memory-3.webp","caption":"Cuidando sus rosas, su mayor pasión","author":"Hija mayor"},{"src":"/memoriales/memory-4.webp","caption":"Vacaciones en la costa, verano del 82","author":"Sobrina Carmen"},{"src":"/memoriales/memory-5.webp","caption":"Cumpleaños número 60","author":"Familia"},{"src":"/memoriales/memory-6.webp","caption":"Atardeceres compartidos de toda una vida","author":"Su esposa"}]'::jsonb, '[{"author":"Gladys, su esposa","text":"Me trajo flores cada lunes durante 58 años. Sin excepción."},{"author":"Pedrito, vecino niño","text":"Sus historias del ''pulpo gigante'' me hacían soñar despierto."},{"author":"Hijo Mario","text":"Me enseñó a leer las estrellas para volver a casa."}]'::jsonb, '[{"type":"Velatorio","date":"Hoy, 18:00 a 22:00 hrs","address":"Parroquia San Luis Gonzaga, Coronel","isoStart":"2026-04-29T18:00:00-03:00","isoEnd":"2026-04-29T22:00:00-03:00","mapsQuery":"Parroquia San Luis Gonzaga, Coronel"},{"type":"Sepultación","date":"Mañana, 11:00 hrs","address":"Cementerio Municipal de Coronel","isoStart":"2026-04-30T11:00:00-03:00","isoEnd":"2026-04-30T12:30:00-03:00","mapsQuery":"Cementerio Municipal de Coronel"}]'::jsonb, 'published', 5)
on conflict (slug) do nothing;

insert into public.condolencias (obituario_id, author_name, message, status)
select o.id, v.name, v.message, 'approved'
from public.obituarios o
cross join (values ('Marcela P.', 'Siempre en nuestros corazones.'), ('Familia Rojas', 'Un abrazo enorme a la familia.'), ('Don Sergio', 'Descansa en paz, viejo amigo.'), ('Carmen L.', null), ('Pablo M.', 'Gracias por todo lo enseñado.')) as v(name, message)
where o.slug = 'carlos-munoz-rivera'
  and not exists (select 1 from public.condolencias c where c.obituario_id = o.id);

insert into public.condolencias (obituario_id, author_name, message, status)
select o.id, v.name, v.message, 'approved'
from public.obituarios o
cross join (values ('Marcela P.', 'Siempre en nuestros corazones.'), ('Familia Rojas', 'Un abrazo enorme a la familia.'), ('Don Sergio', 'Descansa en paz, viejo amigo.'), ('Carmen L.', null), ('Pablo M.', 'Gracias por todo lo enseñado.')) as v(name, message)
where o.slug = 'maria-elena-soto'
  and not exists (select 1 from public.condolencias c where c.obituario_id = o.id);

insert into public.condolencias (obituario_id, author_name, message, status)
select o.id, v.name, v.message, 'approved'
from public.obituarios o
cross join (values ('Marcela P.', 'Siempre en nuestros corazones.'), ('Familia Rojas', 'Un abrazo enorme a la familia.'), ('Don Sergio', 'Descansa en paz, viejo amigo.'), ('Carmen L.', null), ('Pablo M.', 'Gracias por todo lo enseñado.')) as v(name, message)
where o.slug = 'jorge-andres-pereira'
  and not exists (select 1 from public.condolencias c where c.obituario_id = o.id);

insert into public.condolencias (obituario_id, author_name, message, status)
select o.id, v.name, v.message, 'approved'
from public.obituarios o
cross join (values ('Marcela P.', 'Siempre en nuestros corazones.'), ('Familia Rojas', 'Un abrazo enorme a la familia.'), ('Don Sergio', 'Descansa en paz, viejo amigo.'), ('Carmen L.', null), ('Pablo M.', 'Gracias por todo lo enseñado.')) as v(name, message)
where o.slug = 'rosa-vargas-leiva'
  and not exists (select 1 from public.condolencias c where c.obituario_id = o.id);

insert into public.condolencias (obituario_id, author_name, message, status)
select o.id, v.name, v.message, 'approved'
from public.obituarios o
cross join (values ('Marcela P.', 'Siempre en nuestros corazones.'), ('Familia Rojas', 'Un abrazo enorme a la familia.'), ('Don Sergio', 'Descansa en paz, viejo amigo.'), ('Carmen L.', null), ('Pablo M.', 'Gracias por todo lo enseñado.')) as v(name, message)
where o.slug = 'patricia-fuentes-reyes'
  and not exists (select 1 from public.condolencias c where c.obituario_id = o.id);

insert into public.condolencias (obituario_id, author_name, message, status)
select o.id, v.name, v.message, 'approved'
from public.obituarios o
cross join (values ('Marcela P.', 'Siempre en nuestros corazones.'), ('Familia Rojas', 'Un abrazo enorme a la familia.'), ('Don Sergio', 'Descansa en paz, viejo amigo.'), ('Carmen L.', null), ('Pablo M.', 'Gracias por todo lo enseñado.')) as v(name, message)
where o.slug = 'luis-gonzalez-tapia'
  and not exists (select 1 from public.condolencias c where c.obituario_id = o.id);

