/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as CotizarRouteImport } from './routes/cotizar'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObituariosIndexRouteImport } from './routes/obituarios.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ObituariosSlugRouteImport } from './routes/obituarios.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizarRoute = CotizarRouteImport.update({
  id: '/cotizar',
  path: '/cotizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObituariosIndexRoute = ObituariosIndexRouteImport.update({
  id: '/obituarios/',
  path: '/obituarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObituariosSlugRoute = ObituariosSlugRouteImport.update({
  id: '/obituarios/$slug',
  path: '/obituarios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cotizar': typeof CotizarRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/admin/login': typeof AdminLoginRoute
  '/obituarios/$slug': typeof ObituariosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/obituarios/': typeof ObituariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cotizar': typeof CotizarRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/admin/login': typeof AdminLoginRoute
  '/obituarios/$slug': typeof ObituariosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/obituarios': typeof ObituariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cotizar': typeof CotizarRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/admin/login': typeof AdminLoginRoute
  '/obituarios/$slug': typeof ObituariosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/obituarios/': typeof ObituariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/cotizar'
    | '/nosotros'
    | '/servicios'
    | '/admin/login'
    | '/obituarios/$slug'
    | '/admin/'
    | '/obituarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/cotizar'
    | '/nosotros'
    | '/servicios'
    | '/admin/login'
    | '/obituarios/$slug'
    | '/admin'
    | '/obituarios'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/cotizar'
    | '/nosotros'
    | '/servicios'
    | '/admin/login'
    | '/obituarios/$slug'
    | '/admin/'
    | '/obituarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  CotizarRoute: typeof CotizarRoute
  NosotrosRoute: typeof NosotrosRoute
  ServiciosRoute: typeof ServiciosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ObituariosSlugRoute: typeof ObituariosSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ObituariosIndexRoute: typeof ObituariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizar': {
      id: '/cotizar'
      path: '/cotizar'
      fullPath: '/cotizar'
      preLoaderRoute: typeof CotizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obituarios/': {
      id: '/obituarios/'
      path: '/obituarios'
      fullPath: '/obituarios/'
      preLoaderRoute: typeof ObituariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obituarios/$slug': {
      id: '/obituarios/$slug'
      path: '/obituarios/$slug'
      fullPath: '/obituarios/$slug'
      preLoaderRoute: typeof ObituariosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  CotizarRoute: CotizarRoute,
  NosotrosRoute: NosotrosRoute,
  ServiciosRoute: ServiciosRoute,
  AdminLoginRoute: AdminLoginRoute,
  ObituariosSlugRoute: ObituariosSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ObituariosIndexRoute: ObituariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
